import FloatButton from "@/components/ButtonFloat/FloatButton";
import Features from "@/components/Features/Features";
import FooterPage from "@/components/Footer/FooterPage";
import Navbars from "@/components/Navbar/Navbar";
import Villages from "@/components/ProfileVillage/village";
import StrukturDesa from "@/components/StrukturOrganisasi/Sample";
import Youtube from "@/components/Youtube/Sample";
import Publik from "@/components/layananPublik/Sample";
import Head from "next/head";

import Blog from "@/components/Blogs";
import Galeries from "@/components/Galeri";

export default function Home() {
  return (
    <>
      <Head>
        <title>Desa Bandung Banyuwangi </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <Navbars />
        <Villages />
        <Features />
        <StrukturDesa />
        <Youtube />
        <Blog />
        <Galeries />
        <Publik />
        <FloatButton />
        <FooterPage />

        {/*






        */}
      </main>
    </>
  );
}
