import Blog from "@/components/Blogs/Sample";
import Features from "@/components/Features/Features";
import Navbars from "@/components/Navbar/Navbar";
import Villages from "@/components/ProfileVillage/village";
import Youtube from "@/components/Youtube/Sample";
import Publik from "@/components/layananPublik/Sample";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Desa Bandung Banyuwangi </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbars />
      <Villages />
      <Features />
      <Youtube />
      <Blog />
      <Publik />
    </>
  );
}
