import NavPage from "@/components/NavPage/NavPage";
import Button from "designsystem/dist/atom/Button";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";

type Props = {};

function potensidesa({}: Props) {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const { pathname } = useRouter();
  return (
    <>
      <Head>
        <title>Potensi Desa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <NavPage
          className={{
            active: "text-yellow",
            idle: "text-black",
          }}
          cta={
            <>
              <Button className="relative px-8" state="primary">
                <Link href="https://app.desabandung-boyolali.web.id">
                  <a>Masuk</a>
                </Link>
              </Button>
            </>
          }
          pathname={pathname}
        >
          <Link href="/">
            <a>Home</a>
          </Link>
          <Link href="/desa">
            <a>Desa</a>
          </Link>
          <Link href="/potensidesa">
            <a>Potensi Desa</a>
          </Link>
          <Link href="/strukturdesa">
            <a>Struktur Desa</a>
          </Link>
        </NavPage>

        <div className="container mx-auto px-16 mt-10 text-justify">
          <h1 className="underline decoration-pink-500 font-bold text-xl">
            Merti Dusun
          </h1>
          <p className="mb-3 text-gray-500 dark:text-gray-400 mt-5">
            Dalam sebuah perayaan syukuran setelah panen yang penuh makna,
            masyarakat dusun Kebonagung, desa Bandung, menggelar tradisi Merti
            Dusun yang menjadi warisan nenek moyang yang harus dilestarikan.
            Kegiatan ini diselenggarakan secara rutin setiap tahunnya setelah
            panen, sebagai bentuk rasa syukur atas hasil bumi yang melimpah.
            Tahun ini, acara yang seharusnya berlangsung lebih awal namun
            ditunda karena cuaca yang tidak menentu. Merti Dusun adalah acara
            yang dilaksanakan atas dasar rasa syukur atas hasil panen yang
            melimpah, dan dilakukan oleh tiap warga di dusun Kebonagung. Merti
            Dusun erat kaitannya dengan Tumpeng Agung. Tumpeng Agung dimaknai
            sebagai simbol kesatuan masyarakat, menggambarkan bahwa mereka sudah
            merasa cukup dan makmur karena hasil alam yang diberikan.
          </p>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <p className="mb-3 text-gray-500 dark:text-gray-400">
              Kemeriahan Merti Dusun semakin lengkap dengan bancakan dari setiap
              rumah warga, serta adanya gunungan sedekah bumi seperti pisang,
              padi, ketela, hingga kelapa. Beragam hidangan seperti bihun, nasi,
              rempeyek, tempe, gembili, dan ubi dipersiapkan dan kemudian
              dinikmati bersama di lokasi acara. Semua hidangan ini adalah
              simbol kerukunan dan persatuan yang terjalin erat di antara
              masyarakat dusun Kebonagung. Tradisi Merti Dusun merupakan bagian
              dari identitas budaya desa Bandung yang harus dilestarikan.
              &quot;Merti Dusun telah menjadi bagian dari kami sejak zaman nenek
              moyang, dan kami memiliki kewajiban untuk menjaga keberlanjutan
              tradisi ini. Selain sebagai ungkapan rasa syukur, Merti Dusun juga
              mengajarkan tentang gotong royong dan solidaritas di antara warga
              dusun, &quot; ujar Bu Bayan Kebonagung.
            </p>
            <Image
              src="/images/mertidusun.png"
              width={550}
              height={500}
              className="object-cover rounded-xl"
              alt="foto desa"
            />
          </div>
          <p className="mb-3 text-gray-500 dark:text-gray-400">
            Tahun ini, perayaan Merti Dusun berlangsung pada tanggal 15 Juli
            2023. Warga dusun Kebonagung pun merayakannya dengan penuh semangat
            dan kegembiraan. Acara puncak ditandai dengan pemotongan tumpeng
            agung dan penampilan tari tayub, sebuah tarian tradisional Jawa yang
            menghadirkan nuansa klasik dan meriah. Acara Merti Dusun Kebonagung
            menjadi momen yang mengingatkan masyarakat akan pentingnya menjaga
            kearifan lokal dan melestarikan budaya leluhur. Dengan semangat
            gotong royong dan kesederhanaan, mereka menunjukkan bahwa
            kebersamaan adalah kunci dalam mencapai kesejahteraan bagi semua.
            Semoga tradisi Merti Dusun dapat terus berlanjut dan memberikan
            makna yang mendalam bagi generasi mendatang.
          </p>
        </div>
        <div className="container mx-auto px-16 mt-10 text-justify">
          <h1 className="underline decoration-pink-500 font-bold text-xl">
            PENTINGKAH PERAN “IDENTITAS USAHA” UNTUK BRANDING UMKM?
          </h1>
          <p className="mb-3 text-gray-500 dark:text-gray-400 mt-5">
            Setiap perusahaan memiliki identitas yang berfungsi sebagai tanda
            pengenal atau jati diri perusahaan kepada khalayak perusahaan. Pada
            awalnya identitas sebuah perusahaan lebih dikenal masyarakat dalam
            bentuk logo. Menurut Olins (dalam Van Riel 1995:36) identitas
            perusahaan menyatukan perasaan memiliki dan membuatnya dapat
            terlihat.
          </p>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <p className="mb-3 text-gray-500 dark:text-gray-400">
              Identitas juga menawarkan garansi standar kualitas yang konsisten
              dan menyumbangkannya pada loyalitas pelanggan serta kepada target
              grup lainnya. 2 Perusahaan yang memiliki identitas perusahaan yang
              kuat dan meyakinkan mampu mencapai target khalayak yang lebih
              luas. Identitas usaha sangat penting untuk UMKM (Usaha Mikro,
              Kecil, dan Menengah) karena memiliki beberapa peran penting:
              Pembeda: Identitas usaha seperti nama, logo, dan slogan membantu
              membedakan bisnis Anda dari pesaing. Ini membantu dalam membangun
              citra dan kesan yang unik di benak pelanggan. Branding: Identitas
              yang kuat membantu membangun merek yang kuat. Ini menciptakan
              kesan positif pada pelanggan dan meningkatkan loyalitas mereka
              terhadap produk atau layanan Anda. Percaya: Identitas yang
              konsisten dan profesional membantu menciptakan rasa percaya di
              antara pelanggan. Ini penting untuk menarik lebih banyak pelanggan
              dan menjaga hubungan jangka panjang. Marketing: Identitas yang
              menarik dapat menjadi alat pemasaran yang efektif. Saat orang
              melihat logo atau simbol bisnis Anda, mereka akan mengingat produk
              atau layanan yang Anda tawarkan.
            </p>
            <Image
              src="/images/umkm.jpg"
              width={550}
              height={500}
              className="object-cover rounded-xl"
              alt="foto desa"
            />
          </div>
          <p className="mb-3 text-gray-500 dark:text-gray-400">
            Pengenalan: Dengan memiliki identitas yang kuat, bisnis Anda akan
            lebih mudah dikenali dan diingat oleh calon pelanggan, mitra bisnis,
            dan masyarakat luas. Jadi, penting bagi UMKM untuk memiliki
            identitas usaha yang jelas dan kuat sebagai bagian dari strategi
            pemasaran dan pengenalan mereka. Tim 2 KKN Universitas Diponegoro
            2022/2023 telah melakukan penerapan identitas usaha pada UMKM di
            Desa Bandung. Penerapan identitas usaha melalui pembuatan banner
            yang berisi nama usaha, produk usaha, alamat, dan nomor telepon
            pemilik usaha. Selain pembuatan banner untuk UMKM, kami juga
            membuatkan titik google maps UMKM untuk memudahkan calon konsumen
            menemukan lokasi UMKM dan salah satu usaha untuk membranding UMKM di
            Desa Bandung.
          </p>
        </div>
      </main>
    </>
  );
}

export default potensidesa;
