import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Navbar from "designsystem/dist/organism/Navbar";
import Button from "designsystem/dist/atom/Button";
import Link from "next/link";
import { useRouter } from "next/router";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { pathname } = useRouter();
  return (
    <>
      <Head>
        <title>Desa Bandung Banyuwangi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="">
        <Navbar
          className={{
            active: "text-yellow",
            idle: "text-black",
          }}
          cta={
            <>
              <Button className="relative px-8" state="primary">
                <Link href="/">
                  <a>Masuk</a>
                </Link>
              </Button>
            </>
          }
          pathname={pathname}
        >
          <Link href="/">
            <a>Home</a>
          </Link>
          <Link href="/desa">
            <a>Desa</a>
          </Link>
          <Link href="/pemerintah">
            <a>Pemerintahan</a>
          </Link>
          <Link href="/kegiatan">
            <a>Kegiatan</a>
          </Link>
          <Link href="/gallery">
            <a>Galeri</a>
          </Link>
        </Navbar>
      </h1>
    </>
  );
}
